### ISSUE TITLE
Update contributing guidelines for RFC

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#458] opened 2021-12-09 19:34 UTC
At community meeting Stephen suggested - every change should be covered by an RFC, but a single RFC could cover multiple change. It is okay to capture uncertainty in RFC and work iteratively - check out CNCF

**Comment by squeedee** [comment] 2021-12-13 15:53
Dupe of #34

**Closed as completed by squeedee** 2021-12-13 15:53 UTC
Labels: chore
